(defun my-text-mode-hook ()
  (typopunct-mode)
  (linum-mode -1)
  (auto-fill-mode 1)
  (set-input-method "TeX")
  (define-key org-mode-map (kbd "M-s M-q") 'my/begin-end-quote)
  (define-key org-mode-map (kbd "M-s M-v") 'my/begin-end-verse)
  (define-key org-mode-map (kbd "M-s M-x") 'my/begin-end-example)
  (define-key org-mode-map (kbd "M-s M-e") 'my/begin-end-src-emacs-lisp)
  (define-key org-mode-map (kbd "M-s M-r") 'my/begin-end-src-ruby)
)

(add-hook 'text-mode-hook 'my-text-mode-hook)

(defun my-code-mode-hook ()
  (whitespace-mode)
  (linum-mode)
  (typopunct-mode -1))

(add-hook 'ruby-mode-hook 'my-code-mode-hook)
(add-hook 'ruby-mode-hook
  (lambda () (rvm-activate-corresponding-ruby)))
(add-hook 'js-mode-hook 'my-code-mode-hook)
(add-hook 'emacs-lisp-mode-hook 'my-code-mode-hook)
(add-hook 'projectile-mode-hook 'projectile-rails-on)
